# Generated by Django 4.0.4 on 2022-05-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='cards',
            name='last_repetitions_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего повторения'),
        ),
    ]
